apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot-1730196977648
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jrichter/chbot:a69181e2382cc6332d771e3e41b81792d7a2553a@sha256:0ed8674fcc8c9acc034bfcbcafd9ae6a951b8cc509da96e53e3e3c46f34118cc # use pre-built to bootstrap 
          name: app-inference
